/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/App.tsx",
  "./src/pages/login.tsx",
  "./src/pages/myapp.tsx",
  "./src/pages/new_app.tsx",
  "./src/pages/new_fun.tsx",
  "./src/pages/update_app.tsx",
  "./src/pages/update_fun.tsx",
  "./src/pages/guide.tsx",
  "./src/pages/error.tsx",
  "./src/components/Header/header.tsx",
  "./src/components/footer.tsx",
  "./src/components/common/app_main.tsx",
  "./src/components/Main/main_service.tsx",
  "./src/components/Main/main_slide.tsx",
  "./src/components/Login/login_form.tsx",
  "./src/components/app_main.tsx",
  "./src/components/app_info.tsx",
  "./src/components/fun_main.tsx",
  "./src/components/fun_info.tsx",
  "./src/components/update_fun_pre.tsx",
  "./src/components/fun_history.tsx",
],
  theme: {
    extend: {},
  },
  plugins: [],
}
